on:
  push:
    branches: 
      - master

name: Package Extension
jobs: 
  package:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: cmjchrisjones/npm-pkg-github-action@master
